version: "3.1"
services:
    nginx:
        image: 172446528082.dkr.ecr.eu-north-1.amazonaws.com/20210420nginx
        restart: always
        build:
            context: ./nginx
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            - app
    app:
        restart: always
        build: 
            context: .
        image: 172446528082.dkr.ecr.eu-north-1.amazonaws.com/storagehandling
        expose:
        - "8080"
